export const allIconKeys = new Map<string, Set<string>>(
  Object.entries({
    'material-symbols': new Set(['refresh', 'search', 'delete', 'check', 'chevron-right', 'warning-outline']),
    'material-symbols-light': new Set(['connect-without-contact']),
    'svg-spinners': new Set(['3-dots-bounce']),
    fa: new Set([
      'copy',
      'tint',
      'tasks',
      'list',
      'inbox',
      'paper-plane',
      'shield',
      'chevron-right',
      'gear',
      'inbox',
      'dollar',
      'cog',
      'key',
    ]),
    'icon-park-outline': new Set(['file-success-one']),
    'icon-park-solid': new Set(['error']),
    'gravity-ui': new Set(['circle-chevron-right']),
    mdi: new Set([
      'eye-lock-open-outline',
      'house',
      'chevron-down',
      'gas',
      'pound',
      'wallet-add-outline',
      'garbage-can-outline',
      'arrow-right',
    ]),
    lucide: new Set(['contact-round', 'chevron-first', 'chevron-last']),
    hugeicons: new Set(['blockchain-02']),
    icons8: new Set(['chevron-right']),
    'icon-park-twotone': new Set(['broadcast']),
    clarity: new Set(['details-line']),
    iconamoon: new Set(['lock', 'lock-off']),
    'system-uicons': new Set(['write']),
    ph: new Set(['broadcast']),
    ri: new Set(['dice-line']),
    cil: new Set(['contact']),
    majesticons: new Set(['open-line']),
    bx: new Set(['data']),
    ic: new Set(['baseline-plus']),
    bi: new Set(['activity']),
    arcticons: new Set(['mapassist']),
  }),
)
